#!/bin/sh
##############################
#                            #
#   Hytale server launcher   #
#                            #
##############################

# Change this if you want to use a specific IP address or a non standard UDP port
# (for example if running multiple servers on the same machine)
IP="0.0.0.0" # any IP address on the machine
PORT=5520 # standard QUIC port

# Choose one of the following:
JAVA_OPTIONS="--enable-native-access=ALL-UNNAMED"
#JAVA_OPTIONS="--enable-native-access=ALL-UNNAMED -Xms4G -Xmx4G" # small server
#JAVA_OPTIONS="--enable-native-access=ALL-UNNAMED -Xms6G -Xmx8G" # medium server (6-8 GB)
#JAVA_OPTIONS="--enable-native-access=ALL-UNNAMED -Xms10G -Xmx16G -XX:+UseG1GC" # large/public server (10-16 GB)

# Note that we can't use the Ahead-of-Time (AOT) cache as we changed the server Jar...
# (no need to add '-XX:AOTCache=HytaleServer.aot' to JAVA_OPTIONS)

HYTALE_OPTIONS="--backup --backup-dir backups --backup-frequency 30 --bind ${IP}:${PORT}"

################################################################################
# Print parameters as bold yellow text on blue background
################################################################################
InfoMsg()
{
    echo -e "\e[1;33;44m$*\e[0m"
}

################################################################################
# Print parameters as bold yellow text on red background
################################################################################
ErrorMsg()
{
    echo -e "\e[1;33;41m$*\e[0m"
}

################################################################################
# Exit if you're trying to run the script as root
# (bad practice for a server and risk of mixing file owners)
################################################################################
ExitIfRunningAsRoot()
{
    UID=`id -u`
    if [ "${UID}" = "0" ]
    then
        echo
        ErrorMsg "Don't run this as root! Please switch to a user account."
        echo
        exit 1
    fi
}

################################################################################
# Make sure we have the latest version of the Hytale downloader
################################################################################
GetOrUpdateDownloader()
{
    echo
    if [ ! -x hytale-downloader-linux-amd64 ]
    then
        InfoMsg "Getting Hytale downloader:"
        fetch https://downloader.hytale.com/hytale-downloader.zip
        unzip -q hytale-downloader.zip
        rm hytale-downloader-windows-amd64.exe hytale-downloader.zip
        echo
    fi
    hytale-downloader-linux-amd64 -check-update
}

################################################################################
# Run the Hytale downloader interactively the first time so you can provide your
# Hytale credentials
################################################################################
GetDownloaderCredentialsOnFirstLaunch()
# returns true on first launch,
{
    echo
    if [ ! -f .hytale-downloader-credentials.json ]
    then
        # First launch.
        # The downloaded needs to be executed interactively at least once
        # in order to use the "/auth login device" command and generate
        # the .hytale-downloader-credentials.json file
        hytale-downloader-linux-amd64 -print-version 
        echo
        true
    else
        false
    fi
}

################################################################################
# Make a native FreeBSD version of the Netty library
# (mandatory for server execution on FreeBSD)
################################################################################
MakeNetty()
{
    # Determine which version of Netty the server is using
    tar xf HytaleServer.jar META-INF/io.netty.versions.properties
    NETTY_VERSION=`grep "^netty-buffer.version" META-INF/io.netty.versions.properties | sed "s/^.*=//"`
    rm -r META-INF

    # Get and compile Netty, if needed
    if [ ! -f netty-codec-native-quic-${NETTY_VERSION}-freebsd-x86_64.jar ]
    then
        echo
        InfoMsg "Making netty-${NETTY_VERSION}:"
        fetch https://github.com/netty/netty/archive/refs/tags/netty-${NETTY_VERSION}.tar.gz
        tar xzf netty-${NETTY_VERSION}.tar.gz
        cd netty-netty-${NETTY_VERSION}/codec-native-quic/
        mvn clean install -DskipTests -Dlibssl=libssl.a -Dlibcrypto=libcrypto.a -Dlibquiche=libquiche.a
        cp target/netty-codec-native-quic-${NETTY_VERSION}-freebsd-x86_64.jar ../..
        cd ../..
        rm -r netty-${NETTY_VERSION}.tar.gz netty-netty-${NETTY_VERSION} ../.cargo ../.m2
    fi

    # Extract the required FreeBSD native library
    echo
    InfoMsg "Extracting netty-${NETTY_VERSION} shared output library:"
    unzip -j netty-codec-native-quic-${NETTY_VERSION}-freebsd-x86_64.jar META-INF/native/libnetty_quiche42_freebsd_x86_64.so
    echo
}

################################################################################
# Download the CFR decompiler
################################################################################
GetCfr()
{
    if [ ! -f cfr-0.152.jar ]
    then
        InfoMsg "Downloading the CFR decompiler"
        fetch https://github.com/leibnitz27/cfr/releases/download/0.152/cfr-0.152.jar
    fi
}

################################################################################
# Patch the Hytale server jar file
################################################################################
PatchServer()
{
    cd Server

    MakeNetty

    GetCfr

    mkdir WORK
    cd WORK

    InfoMsg "Extracting files from HytaleServer.jar"
    tar xzf ../HytaleServer.jar

    InfoMsg "Decompiling classes we need to patch:"
    java -jar ../cfr-0.152.jar com/hypixel/hytale/common/util/*.class --outputdir .

    InfoMsg "Patching decompiled sources:"
    patch < ../../SystemUtil.diff
    patch < ../../HardwareUtil.diff

    InfoMsg "Recompiling patched sources"
    javac com/hypixel/hytale/common/util/SystemUtil.java
    javac com/hypixel/hytale/common/util/HardwareUtil.java

    InfoMsg "Injecting FreeBSD native netty library"
    mv ../libnetty_quiche42_freebsd_x86_64.so META-INF/native/

    InfoMsg "Removing other operating systems libraries"
    rm -r aix darwin linux win
    rm librocksdbjni-linux* librocksdbjni-osx* librocksdbjni-win*

    InfoMsg "Cleaning work directory"
    find . -name "*.java" -exec rm {} \;
    find . -name "*.orig" -exec rm {} \;

    InfoMsg "Rebuilding HytaleServer.jar with the patched classes and netty for FreeBSD"
    jar cmf META-INF/MANIFEST.MF ../HytaleServer.jar .

    cd ..
    rm -r WORK
}

################################################################################
# Get and patch a new Hytale server version if there is one
################################################################################
GetOrUpdateAndPatchServer()
{
    LATEST_HYTALE_VERSION=`hytale-downloader-linux-amd64 -print-version`
    if [ ! -f ${LATEST_HYTALE_VERSION}.zip ]
    then
        InfoMsg "Getting Hytale server latest version:"
        hytale-downloader-linux-amd64
    
        if [ -d Server ]
        then
            InfoMsg "Backing up previous version"

            if [ ! -d previous_version ]
            then
                mkdir previous_version
            else
                rm -rf previous_version/*
            fi

            mv Server/HytaleServer.* previous_version
            mv Server/Licenses previous_version
            mv Assets.zip previous_version
        fi

        InfoMsg "Installing the new version:"
        unzip ${LATEST_HYTALE_VERSION}.zip
        rm start.bat start.sh

        InfoMsg "Patching the server jar file:"
        PatchServer
        echo
    fi
    echo "Hytale is up to date (${LATEST_HYTALE_VERSION})"
    echo
}

################################################################################
# Find a mod filename from its GROUP:NAME: signature
################################################################################
FindModNameFromSignature()
{
    for PATHNAME in `find mods -type f -depth 1`
    do
        tar xzf "${PATHNAME}" manifest.json
        if [ -f manifest.json ]
        then
            GROUP=`grep "\"Group\":" manifest.json | head -1 | sed -e "s/\",$//" -e "s/.*\"//"`
            NAME=`grep "\"Name\":" manifest.json | head -1 | sed -e "s/\",$//" -e "s/.*\"//"`
            rm manifest.json
            if [ "$1" = "${GROUP}:${NAME}" ]
            then
                echo "${PATHNAME}" | sed "s,mods/,,"
                break
            fi
        fi
    done
}

################################################################################
# The main function. Start here
################################################################################
main()
{
    ExitIfRunningAsRoot
    GetOrUpdateDownloader
    if GetDownloaderCredentialsOnFirstLaunch
    then
        FIRST_LAUNCH="true"
    else
        FIRST_LAUNCH="false"
    fi
    GetOrUpdateAndPatchServer
    sleep 1

    if [ "${FIRST_LAUNCH}" = "true" ]
    then
        InfoMsg "Now we'll make the initial launch of the server."
        InfoMsg "In the console, type '/auth login device' to activate it,"
        InfoMsg "then type '/auth persistence Encrypted' to store your credentials,"
        InfoMsg "then type '/stop' to stop the server."
        echo
        InfoMsg "Next get into the "Server" sub-directory and configure your server."
        InfoMsg "Check https://hytale.game/en/create-server-hytale-guide/ for guidance"
        echo
        InfoMsg "The server will be updated (if needed) and launched next times you call this script."
        echo
        sleep 5
    fi

    cd Server
    while true
    do
        InfoMsg "Launching the Hytale server"
        java ${JAVA_OPTIONS} -jar HytaleServer.jar --assets ../Assets.zip ${HYTALE_OPTIONS}
        EXIT_CODE=$?

        if [ ${EXIT_CODE} = "0" ]
        then
            InfoMsg "Operator issued the /stop command."
            InfoMsg "The server will have to be relaunched manually."
            exit 0
        else
            ErrorMsg "The server exited with a ${EXIT_CODE} exit code."

            LAST_LOGFILE=logs/`ls -1rt logs | tail -1`
            CRASHING_MOD=`grep " potentially caused by " ${LAST_LOGFILE} | sed -e "s/.* potentially caused by //" -e "s/:$//"`
            if [ $? = "0" ]
            then
                ErrorMsg "The '${CRASHING_MOD}' mod seems to crash the server:"
                awk '/ potentially caused by / {FOUND=1} !NF && FOUND==1 {exit} FOUND==1 {print}' ${LAST_LOGFILE}

                MOD_NAME=`FindModNameFromSignature "${CRASHING_MOD}"`
                if [ "${MOD_NAME}" != "" ]
                then
                    ErrorMsg "Moving ${MOD_NAME} to Server/mods/.disabled to disable it!"
                    mkdir -p mods/.disabled
                    mv -f "mods/${MOD_NAME}" mods/.disabled 
                    ErrorMsg "Update it!"
                else
                    ErrorMsg "Update it or disable it!"
                fi
                ErrorMsg "The server will have to be relaunched manually."
                exit ${EXIT_CODE}
            fi

            ErrorMsg "Trying to relaunch the server automatically."
        fi
    done
}

main
